# Generated by Django 4.2.11 on 2024-03-19 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_type', models.CharField(max_length=50)),
                ('game_name', models.CharField(max_length=50)),
                ('game_description', models.TextField()),
                ('result', models.CharField(max_length=50)),
                ('ball', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('wallet', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('upi_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='UserGameData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_type', models.CharField(max_length=50)),
                ('type_of_bet', models.CharField(max_length=50)),
                ('bet', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('win_or_lose', models.CharField(blank=True, max_length=50, null=True)),
                ('winning_amount', models.IntegerField(blank=True, null=True)),
                ('winning_number', models.CharField(blank=True, max_length=50, null=True)),
                ('winning_color', models.CharField(blank=True, max_length=50, null=True)),
                ('winning_ball', models.CharField(blank=True, max_length=50, null=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.gamedetail')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='UserBankDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_type', models.CharField(max_length=50)),
                ('winning_number', models.CharField(max_length=50)),
                ('winning_color', models.CharField(max_length=50)),
                ('winning_ball', models.CharField(max_length=50)),
                ('total_bet_amount', models.FloatField()),
                ('total_win_amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_results', to='user_registration.gamedetail')),
            ],
        ),
        migrations.CreateModel(
            name='liveUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=50)),
                ('flag', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.userdetail')),
            ],
        ),
    ]
