# Generated by Django 4.2.11 on 2024-03-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='wallet',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usergamedata',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usergamedata',
            name='winning_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpaymentmodel',
            name='amount',
            field=models.FloatField(),
        ),
    ]
