# Generated by Django 4.2.11 on 2024-03-23 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0002_alter_userdetail_wallet_alter_usergamedata_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserwithdrawHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.userbankdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.userdetail')),
            ],
        ),
    ]
