# Generated by Django 4.2.11 on 2024-03-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0003_userwithdrawhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
