# Generated by Django 4.2.11 on 2024-03-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0004_alter_gamedetail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedetail',
            name='new_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
