# Generated by Django 4.2.11 on 2024-03-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0005_gamedetail_new_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedetail',
            name='new_date',
        ),
    ]
